apiVersion: apps/v1
kind: Deployment
metadata:
  name: citi-deployment-app
spec:
  selector:
    matchLabels:
      app: citi
  template:
    metadata:
      labels:
        app: citi
    spec:
      containers:
      - name: citi-container
        image: muralisocial123/web-app:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "100Mi"  
            cpu: "100m"
        ports:
        - containerPort: 80
--- 
apiVersion: v1 
kind: Service
metadata:
  name: citi-deployment-svc
spec:
  selector:
    app: citi
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer  
--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: citi-autoscaling 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: citi-deployment-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  
        